title: 'Kaio Fabian - Tecnologias Blockchain'
description: 'Sou um entusiasta das tecnologias Bitcoin e Blockchain. Esse site é focado em um conjunto de validadores e serviços essenciais que apóio e contribuo para a segurança em diferentes Blockchains.' # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "/validators" # the subpath of your site, e.g. /blog /flexible-jekyll /validators
url: "kaiofabian.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: kaiofabian
social-linkedin: kaiofabian

# Author Settings
author: Kaio Fabian # add your name
author-img: kaiofabian.png # add your photo
about-author: 'Sou um entusiasta das tecnologias Bitcoin e Blockchain. Esse site é focado em um conjunto de validadores e serviços essenciais que apóio e contribuo para a segurança em diferentes Blockchains.' # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: kaiofabian # add your Github handle
social-medium: kaiofabian
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
